observation_bmi_gs_mapping_ktb = {
    "multi_resource_per_row_bool": True,
    "subject_metadata_file": "barcode_SID_ktb.csv",
    "files": {
        "bmi_and_gail.csv": {
            "skip_first_line": True,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "bmi"], ["barcode", "gail"],],
        },
        "birth_year_don_year.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "donation year"]],
        },
        "subject_id_barcode_2.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "subject_id"]],
        },
    },
    "target_mappings": {"SID": ["subject_id", "barcode"],},
    "value_mappings": ["bmi", "gail",],
    "value_type_mappings": ["kg/m2", "%",],
    "date_mappings": ["donation year", "donation year",],
    "column_headers": [
        "SID",
        "VALUE",
        "VALUE_CODE",
        "VALUE_TYPE",
        "VALUE_DATE",
        "subject",
    ],
}

observation_mapping_ktb = {
    "multi_resource_per_row_bool": True,
    "subject_metadata_file": "barcode_SID_ktb.csv",
    "files": {
        "lifeomic-export-non-phi.csv": {
            "skip_first_line": False,
            "first_line_metadata": True,
            "multiple_columns_to_keep": [
                ["barcode", "agediag"],
                ["barcode", "agefrsbr"],
                ["barcode", "age_at_max_ht"],
                ["barcode", "age_of_reg_menst_pd"],
                ["barcode", "age_when_eval_acne"],
                ["barcode", "ai_age_current"],
                ["barcode", "ai_age_eightt_twentwo"],
                ["barcode", "ai_age_fourt_sevent"],
                ["barcode", "ai_age_ltfourt"],
                ["barcode", "ai_age_thirt_thirtfour"],
                ["barcode", "ai_age_twenthree_twennine"],
                ["barcode", "ashkjwsh"],
                ["barcode", "biltmast"],
                ["barcode", "biolther"],
                ["barcode", "biolther_2"],
                ["barcode", "bldfamca"],
                ["barcode", "body_shape"],
                ["barcode", "body_size_age_five"],
                ["barcode", "body_size_age_ten"],
                ["barcode", "body_size_age_twenty"],
                ["barcode", "brca1"],
                ["barcode", "brca2"],
                ["barcode", "brcatyp"],
                ["barcode", "breastca"],
                ["barcode", "breastfd"],
                ["barcode", "breast_buds"],
                ["barcode", "breldona"],
                ["barcode", "bresbiop"],
                ["barcode", "brfdmons"],
                ["barcode", "chemomet"],
                ["barcode", "chemothr"],
                ["barcode", "chest_circ"],
                ["barcode", "cigprday"],
                ["barcode", "cup_size"],
                ["barcode", "curtbreastfd"],
                ["barcode", "curtdrnk"],
                ["barcode", "curthorm"],
                ["barcode", "curtpreg"],
                ["barcode", "curtsmkr"],
                ["barcode", "datediagnosed"],
                ["barcode", "drinskwk"],
                ["barcode", "educatn"],
                ["barcode", "erstatus"],
                ["barcode", "etohyrs"],
                ["barcode", "evertobc"],
                ["barcode", "ex_moderate_dpw"],
                ["barcode", "ex_moderate_hours"],
                ["barcode", "ex_moderate_mins"],
                ["barcode", "ex_sitting_hours"],
                ["barcode", "ex_sitting_mins"],
                ["barcode", "ex_vigorous_dpw"],
                ["barcode", "ex_vigorous_hours"],
                ["barcode", "ex_vigorous_mins"],
                ["barcode", "ex_walk_dpw"],
                ["barcode", "ex_walk_hours"],
                ["barcode", "ex_walk_mins"],
                ["barcode", "first_sign"],
                ["barcode", "food_prior"],
                ["barcode", "frmenage"],
                ["barcode", "generisk"],
                ["barcode", "her2stat"],
                ["barcode", "hhincome"],
                ["barcode", "hiscancr"],
                ["barcode", "horhowlg"],
                ["barcode", "hormmet"],
                ["barcode", "hormther"],
                ["barcode", "horrplth"],
                ["barcode", "hotflash"],
                ["barcode", "htfeet"],
                ["barcode", "htinches"],
                ["barcode", "leftbr"],
                ["barcode", "length_of_pd"],
                ["barcode", "lstprddt"],
                ["barcode", "lstprdyr"],
                ["barcode", "lumptomy"],
                ["barcode", "lvbirths"],
                ["barcode", "lymedema"],
                ["barcode", "lymphnod"],
                ["barcode", "mamo12mo"],
                ["barcode", "mamogram"],
                ["barcode", "mamonorm"],
                ["barcode", "masttomy"],
                ["barcode", "med_eval_for_acne"],
                ["barcode", "mensstat"],
                ["barcode", "metadgdt"],
                ["barcode", "metastat"],
                ["barcode", "mod_age_current"],
                ["barcode", "mod_age_eightt_twentwo"],
                ["barcode", "mod_age_fourt_sevent"],
                ["barcode", "mod_age_ltfourt"],
                ["barcode", "mod_age_thirt_thirtfour"],
                ["barcode", "mod_age_twenthree_twennine"],
                ["barcode", "datediagnosed"],
                ["barcode", "numbiop"],
                ["barcode", "numlymnd"],
                ["barcode", "num_cig"],
                ["barcode", "oc_age_current"],
                ["barcode", "oc_age_eightt_twentwo"],
                ["barcode", "oc_age_fourt_sevent"],
                ["barcode", "oc_age_ltfourt"],
                ["barcode", "oc_age_thirt_thirtfour"],
                ["barcode", "oc_age_twenthree_twennine"],
                ["barcode", "othrskfa"],
                ["barcode", "ovaryone"],
                ["barcode", "ovarytwo"],
                ["barcode", "ovroneyr"],
                ["barcode", "ovrtwoyr"],
                ["barcode", "pregnant"],
                ["barcode", "pregtms"],
                ["barcode", "prevdona"],
                ["barcode", "prevdona_side"],
                ["barcode", "prevdona_type"],
                ["barcode", "prophybm"],
                ["barcode", "prstatus"],
                ["barcode", "pubic_hair"],
                ["barcode", "quityr"],
                ["barcode", "race"],
                ["barcode", "radtherp"],
                ["barcode", "reg_menst_pd"],
                ["barcode", "res_descrip"],
                ["barcode", "rightbr"],
                ["barcode", "secbrca"],
                ["barcode", "since_breastfeed"],
                ["barcode", "stopbreastfdlst6mons"],
                ["barcode", "stopbreastfdmons"],
                ["barcode", "stren_age_current"],
                ["barcode", "stren_age_eightt_twentwo"],
                ["barcode", "stren_age_fourt_sevent"],
                ["barcode", "stren_age_ltfourt"],
                ["barcode", "stren_age_thirt_thirtfour"],
                ["barcode", "stren_age_twenthree_twennine"],
                ["barcode", "surgery"],
                ["barcode", "syndroms"],
                ["barcode", "syndroms_2"],
                ["barcode", "syndroms_2_2"],
                ["barcode", "s_age_current"],
                ["barcode", "s_age_eightt_twentwo"],
                ["barcode", "s_age_fourt_sevent"],
                ["barcode", "s_age_ltfourt"],
                ["barcode", "s_age_thirt_thirtfour"],
                ["barcode", "s_age_twenthree_twennine"],
                ["barcode", "take_meds_acne"],
                ["barcode", "testpos"],
                ["barcode", "tobcyrs"],
                ["barcode", "tsposoth"],
                ["barcode", "typehorm"],
                ["barcode", "typsecca"],
                ["barcode", "weekofpreg"],
                ["barcode", "weight"],
                ["barcode", "weight_at_eighteen"],
                ["barcode", "workstat"],
                ["barcode", "w_age_current"],
                ["barcode", "w_age_eightt_twentwo"],
                ["barcode", "w_age_fourt_sevent"],
                ["barcode", "w_age_ltfourt"],
                ["barcode", "w_age_thirt_thirtfour"],
                ["barcode", "w_age_twenthree_twennine"],
                ["barcode", "yearlastmamo"],
            ],
        },
        "birth_year_don_year.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "donation year"]],
        },
        "subject_id_barcode_2.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "subject_id"]],
        },
    },
    "target_mappings": {
        "SID": ["subject_id", "barcode"],
        "CODE_DESC": ["first_line_metadata"],
    },
    "value_mappings": [
        "agediag",
        "agefrsbr",
        "age_at_max_ht",
        "age_of_reg_menst_pd",
        "age_when_eval_acne",
        "ai_age_current",
        "ai_age_eightt_twentwo",
        "ai_age_fourt_sevent",
        "ai_age_ltfourt",
        "ai_age_thirt_thirtfour",
        "ai_age_twenthree_twennine",
        "ashkjwsh",
        "biltmast",
        "biolther",
        "biolther_2",
        "bldfamca",
        "body_shape",
        "body_size_age_five",
        "body_size_age_ten",
        "body_size_age_twenty",
        "brca1",
        "brca2",
        "breastca",
        "breastfd",
        "breast_buds",
        "breldona",
        "bresbiop",
        "brfdmons",
        "chemomet",
        "chemothr",
        "chest_circ",
        "cigprday",
        "cup_size",
        "curtbreastfd",
        "curtdrnk",
        "curthorm",
        "curtpreg",
        "curtsmkr",
        "drinskwk",
        "educatn",
        "erstatus",
        "etohyrs",
        "evertobc",
        "ex_moderate_dpw",
        "ex_moderate_hours",
        "ex_moderate_mins",
        "ex_sitting_hours",
        "ex_sitting_mins",
        "ex_vigorous_dpw",
        "ex_vigorous_hours",
        "ex_vigorous_mins",
        "ex_walk_dpw",
        "ex_walk_hours",
        "ex_walk_mins",
        "first_sign",
        "food_prior",
        "frmenage",
        "generisk",
        "her2stat",
        "hhincome",
        "hiscancr",
        "horhowlg",
        "hormmet",
        "hormther",
        "horrplth",
        "hotflash",
        "htfeet",
        "htinches",
        "leftbr",
        "length_of_pd",
        "lstprddt",
        "lstprdyr",
        "lumptomy",
        "lvbirths",
        "lymedema",
        "lymphnod",
        "mamo12mo",
        "mamogram",
        "mamonorm",
        "masttomy",
        "med_eval_for_acne",
        "mensstat",
        "metadgdt",
        "metastat",
        "mod_age_current",
        "mod_age_eightt_twentwo",
        "mod_age_fourt_sevent",
        "mod_age_ltfourt",
        "mod_age_thirt_thirtfour",
        "mod_age_twenthree_twennine",
        "numbiop",
        "numlymnd",
        "num_cig",
        "oc_age_current",
        "oc_age_eightt_twentwo",
        "oc_age_fourt_sevent",
        "oc_age_ltfourt",
        "oc_age_thirt_thirtfour",
        "oc_age_twenthree_twennine",
        "othrskfa",
        "ovaryone",
        "ovarytwo",
        "pregnant",
        "pregtms",
        "prevdona",
        "prevdona_side",
        "prevdona_type",
        "prophybm",
        "prstatus",
        "pubic_hair",
        "quityr",
        "race",
        "radtherp",
        "reg_menst_pd",
        "res_descrip",
        "rightbr",
        "secbrca",
        "since_breastfeed",
        "stopbreastfdlst6mons",
        "stopbreastfdmons",
        "stren_age_current",
        "stren_age_eightt_twentwo",
        "stren_age_fourt_sevent",
        "stren_age_ltfourt",
        "stren_age_thirt_thirtfour",
        "stren_age_twenthree_twennine",
        "surgery",
        "syndroms",
        "syndroms_2",
        "syndroms_2_2",
        "s_age_current",
        "s_age_eightt_twentwo",
        "s_age_fourt_sevent",
        "s_age_ltfourt",
        "s_age_thirt_thirtfour",
        "s_age_twenthree_twennine",
        "take_meds_acne",
        "testpos",
        "tobcyrs",
        "tsposoth",
        "typehorm",
        "typsecca",
        "weekofpreg",
        "weight",
        "weight_at_eighteen",
        "workstat",
        "w_age_current",
        "w_age_eightt_twentwo",
        "w_age_fourt_sevent",
        "w_age_ltfourt",
        "w_age_thirt_thirtfour",
        "w_age_twenthree_twennine",
        "yearlastmamo",
    ],
    "value_type_mappings": [
        "year",
        "year",
        "year",
        "year",
        "year",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "year",
        "",
        "",
        "month",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "year",
        "",
        "days per week",
        "hour",
        "minute",
        "hour",
        "minute",
        "days per week",
        "hour",
        "minute",
        "days per week",
        "hour",
        "minute",
        "",
        "",
        "year",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Feet",
        "inch",
        "",
        "day",
        "",
        "",
        "",
        "#",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "#",
        "#",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "#",
        "",
        "",
        "",
        "",
        "",
        "year",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "month",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "week",
        "pound",
        "pound",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "date_mappings": [
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "ovroneyr",
        "ovrtwoyr",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
        "donation year",
    ],  # need to restructure to account for differing lengths of lists between value and date
    "column_headers": [
        "SID",
        "VALUE",
        "VALUE_CODE",
        "CODE_DESC",
        "VALUE_TYPE",
        "VALUE_DATE",
        "subject",
    ],
}


medication_mapping_ktb = {
    "multi_resource_per_row_bool": True,
    "files": {
        "lifeomic-export-non-phi.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "medicationtaking"]],
        },
        "birth_year_don_year.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "donation year"]],
        },
        "subject_id_barcode_2.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "subject_id"]],
        },
    },
    "subject_metadata_file": "barcode_SID_ktb.csv",
    "target_mappings": {
        "SID": ["subject_id", "barcode"],
        "DRUG_NAME": ["medicationtaking"],
        "DRUG_CODE": [],
        # "CODE_DESC": ["first_line_metadata"],
        "START_DATE": ["donation year"],
        # "subject": ["ID"],
    },
    "date_mappings": [
        "donation year",
    ],  # need to restructure to account for differing lengths of lists between value and date
    "transpose_mappings": [
        {
            "mapping_name": "medicationtaking",
            "mapping_delimiter": ",",
            "secondary_mapping_delimiter": "-",
        }
    ],
    "column_headers": [
        "SID",
        "DRUG_NAME",
        "DRUG_CODE",
        # "CODE_DESC",
        "START_DATE",
        "subject",
    ],
}

medication_mapping_test = {
    "multi_resource_per_row_bool": True,
    "files": {
        "test_komen.csv": {
            "skip_first_line": False,
            "first_line_metadata": True,
            "multiple_columns_to_keep": [["barcode", "medicationtaking"]],
        },
        "test_donation_year.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "donation year"]],
        },
        "test_subject_id.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "subject_id"]],
        },
    },
    "target_mappings": {
        "SID": ["subject_id", "barcode"],
        "DRUG_NAME": ["medicationtaking"],
        "DRUG_CODE": [],
        "CODE_DESC": ["first_line_metadata"],
        "START_DATE": ["donation year"],
    },
    "date_mappings": [
        "donation year",
    ],  # need to restructure to account for differing lengths of lists between value and date
    "transpose_mappings": [
        {
            "mapping_name": "medicationtaking",
            "mapping_delimiter": ",",
            "secondary_mapping_delimiter": "-",
        }
    ],
    "column_headers": ["SID", "DRUG_NAME", "DRUG_CODE", "CODE_DESC", "START_DATE"],
}


# condition_mapping_test = {
#     "multi_resource_per_row_bool": True,
#     "subject_metadata_file": "barcode_SID_ktb.csv",
#     "files": {
#         "test_komen.csv": {
#             "lifeomic-export-non-phi.csv": True,
#             "first_line_metadata": False,
#             "multiple_columns_to_keep": [["barcode", "cancer"],],
#         },
#         "test_donation_year.csv": {
#             "skip_first_line": False,
#             "multiple_columns_to_keep": [["barcode", "donation year"]],
#         },
#         "test_subject_id.csv": {
#             "skip_first_line": False,
#             "multiple_columns_to_keep": [["barcode", "subject_id"]],
#         },
#     },
#     "target_mappings": {
#         "SID": ["subject_id", "barcode"],
#         "CONDITION_NAME": ["cancer"],
#         "START_DATE": ["donation year"],
#     },
#     "date_mappings": [
#         "donation year",
#     ],  # need to restructure to account for differing lengths of lists between value and date
#     "transpose_mappings": [{"mapping_name": "cancer", "mapping_delimiter": ","}],
#     "column_headers": ["SID", "CONDITION_NAME", "START_DATE", "subject"],
# }


condition_mapping_ktb = {
    "multi_resource_per_row_bool": True,
    "subject_metadata_file": "barcode_SID_ktb.csv",
    "files": {
        "lifeomic-export-non-phi.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "cancer"], ["barcode", "disease"]],
        },
        "birth_year_don_year.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "donation year"]],
        },
        "subject_id_barcode_2.csv": {
            "skip_first_line": False,
            "first_line_metadata": False,
            "multiple_columns_to_keep": [["barcode", "subject_id"]],
        },
    },
    "target_mappings": {
        "SID": ["subject_id", "barcode"],
        "CONDITION_NAME": ["cancer", "disease"],
        "START_DATE": ["donation year"],
    },
    "value_mappings": ["cancer", "disease",],
    "date_mappings": [
        "donation year",
        "donation year",
    ],  # need to restructure to account for differing lengths of lists between value and date
    "transpose_mappings": [
        {"mapping_name": "cancer", "mapping_delimiter": ","},
        {"mapping_name": "disease", "mapping_delimiter": ","},
    ],
    "column_headers": ["SID", "CONDITION_NAME", "START_DATE", "subject"],
}

patient_mapping_1 = {
    "multi_file_transform_bool": False,
    "files": {
        "lifeomic-export-non-phi.csv": {
            "skip_first_line": True,
            "columns_to_keep": ["barcode", "humanrace", "hispanic", "martstat"],
        },
        "birth_year_don_year.csv": {
            "skip_first_line": False,
            "columns_to_keep": ["barcode", "birth year"],
        },
        "subject_id_barcode_2.csv": {
            "skip_first_line": False,
            "columns_to_keep": ["barcode", "subject_id"],
        },
    },
    "mappings": {
        "SID": ["subject_id", "barcode"],
        "RACE": ["humanrace"],
        "ETHNICITY": ["hispanic"],
        "BIRTH_DATE": ["birth year"],
        "MARITAL_STATUS": ["martstat"],
    },
    "column_headers": ["SID", "RACE", "ETHNICITY", "BIRTH_DATE", "MARITAL_STATUS"],
}


medication_mapping = {
    "files": {
        "locked.csv": {
            "multiple_columns_to_keep": [
                [
                    "NEW UNIQUE CODE #",
                    "Name of drug(1)",
                    "If other, please specify(1)",
                    "Route(1)",
                    "Indication(1)",
                    "NCT number(1)",
                    "Date started (1) from test order date (BK) (days)",
                    "Ongoing?(1)",
                    "Date stopped (1) from test order date (BK)(days)",
                    "Reason for stopping(1)",
                    "DAY 0 Test Order Date (Year only)",
                ]
            ]
        }
    },
    "mappings": {
        "SID": ["NEW UNIQUE CODE #"],
        "DRUG_NAME": ["Name of drug(1)", "If other, please specify(1)"],
        "ROUTE": ["Route(1)"],
        "INDICATION": ["Indication(1)"],
        "NCT": ["NCT number(1)"],
        "START_DATE": ["Date started (1) from test order date (BK) (days)"],
        "ONGOING": ["Ongoing?(1)"],
        "END_DATE": ["Date stopped (1) from test order date (BK)(days)"],
        "STATUS_REASON": ["Reason for stopping(1)"],
        "REFERENCE_DATE": ["DAY 0 Test Order Date (Year only)"],
    },
    "column_headers": [
        "SID",
        "DRUG_NAME",
        "ROUTE",
        "INDICATION",
        "NCT",
        "START_DATE",
        "ONGOING",
        "END_DATE",
        "STATUS_REASON",
        "REFERENCE_DATE",
    ],
}

medication2_mapping = {
    "files": {
        "drugs.csv": {
            "multiple_columns_to_keep": [
                [
                    "NEW UNIQUE CODE #",
                    "Name of drug",
                    "Route",
                    "Indication",
                    "NCT number",
                    "Date started",
                    "Ongoing",
                    "Date stopped",
                    "Reason for stopping",
                    "Reference date",
                ]
            ]
        }
    },
    "mappings": {
        "SID": ["NEW UNIQUE CODE #"],
        "DRUG_NAME": ["Name of drug"],
        "ROUTE": ["Route"],
        "INDICATION": ["Indication"],
        "NCT": ["NCT number"],
        "START_DATE": ["Date started"],
        "ONGOING": ["Ongoing"],
        "END_DATE": ["Date stopped"],
        "STATUS_REASON": ["Reason for stopping"],
        "REFERENCE_DATE": ["Reference date"],
    },
    "column_headers": [
        "SID",
        "DRUG_NAME",
        "ROUTE",
        "INDICATION",
        "NCT",
        "START_DATE",
        "ONGOING",
        "END_DATE",
        "STATUS_REASON",
        "REFERENCE_DATE",
    ],
}

condition_mapping = {
    "files": {
        "001_FINAL de-identified MCGI 2019 0729 Brain Tumor ALL Data.2019.08.23. locked.csv": {
            "multiple_columns_to_keep": [
                [
                    "NEW UNIQUE CODE #",
                    "Site of current cancer(1)",
                    "Other, please specify(1)",
                    "Date of diagnosis(1) relative to test order date (BK)(days)",
                    "Clinical stage(1)",
                    "Diagnosis",
                    "DAY 0 Test Order Date (Year only)",
                ]
            ]
        }
    },
    "mappings": {
        "SID": ["NEW UNIQUE CODE #"],
        "SITE": ["Site of current cancer(1)", "Other, please specify(1)"],
        "DATE_OF_DX": ["Date of diagnosis(1) relative to test order date (BK)(days)"],
        "STAGE": ["Clinical stage(1)"],
        "DX": ["Diagnosis"],
        "REFERENCE_DATE": ["DAY 0 Test Order Date (Year only)"],
    },
    "column_headers": ["SID", "SITE", "DATE_OF_DX", "STAGE", "DX", "REFERENCE_DATE"],
}


procedure_mapping = {
    "files": {
        "001_FINAL de-identified MCGI 2019 0729 Brain Tumor ALL Data.2019.08.23. locked.csv": {
            "multiple_columns_to_keep": [
                [
                    "NEW UNIQUE CODE #",
                    "Report from test order date (BK) (days)",
                    "Test Type",
                    "Ordering Clinician",
                    "Clinician credential",
                    "Practice Name",
                ]
            ]
        }
    },
    "mappings": {
        "SID": ["NEW UNIQUE CODE #"],
        "SITE": ["Site of current cancer(1)", "Other, please specify(1)"],
        "DATE_OF_DX": ["Date of diagnosis(1) relative to test order date (BK)(days)"],
        "STAGE": ["Clinical stage(1)"],
        "DX": ["NCT number(1)"],
        "REFERENCE_DATE": ["DAY 0 Test Order Date (Year only)"],
    },
    "column_headers": ["SID", "SITE", "DATE_OF_DX", "STAGE", "DX", "REFERENCE_DATE"],
}


observation_mapping_1 = {
    "files": {
        "locked.csv": {
            "multiple_columns_to_keep": [
                [
                    "NEW UNIQUE CODE #",
                    "Report from test order date (BK) (days)",
                    "Test Type",
                    "Ordering Clinician",
                    "Clinician credential",
                    "Practice Name",
                ]
            ],
            "multiple_observation_per_cell": [
                [
                    {"column_header": "NEW UNIQUE CODE #"},
                    {
                        "column_header": "Clinically Significant Aberrations-from Test Report (TR)",
                        "delimiter": "\n",
                    },
                    {"column_header": "Test Type"},
                    {"column_header": "Ordering Clinician"},
                    {"column_header": "Clinician credential"},
                    {"column_header": "Practice Name"},
                ]
            ],
        }
    },
    "mappings": {
        "SID": ["NEW UNIQUE CODE #"],
        "SITE": ["Site of current cancer(1)", "Other, please specify(1)"],
        "DATE_OF_DX": ["Date of diagnosis(1) relative to test order date (BK)(days)"],
        "STAGE": ["Clinical stage(1)"],
        "DX": ["NCT number(1)"],
        "REFERENCE_DATE": ["DAY 0 Test Order Date (Year only)"],
    },
    "column_headers": ["SID", "SITE", "DATE_OF_DX", "STAGE", "DX", "REFERENCE_DATE"],
}
